#!/usr/bin/perl
#==============================================================================#
# POD                                                                          #
#==============================================================================#
# {{{
=encoding utf-8

=head1 NAME

B<album> - Tratamiento de nuevo album de fotos

=head1 SYNOPSIS

=over 4

=item album [-h|--help|-u|-V|--version]

=item album [-v] [-t] [-r] [-g] F<FILE>

=back

=head1 DESCRIPTION

Tratamiento de nuevo album de fotos

=head1 OPTIONS

=over 4

=item B<-g>

General. No familiar.

=item B<-h>, B<--help>

Muestra la información de ayuda completa.

=item B<-r>

Con renrot.

=item B<-t>

Test Mode. No ejecuta. Sólo muestra los comandos.

=item B<-u>

Muestra la información básica de uso (SYNOPSIS).

=item B<-v>

Muestra información detallada durante la ejecución.

=item B<-V>, B<--version>

Muestra la versión del comando y los módulos usados.

=back

=head1 FILES

=over 4

=item Directorio destino thumbnails: F<$HOME/Dropbox/Familiar>

=item Directorio almacen de fotos: F</pub/fotos>

=back

=head1 DEPENDENCIES

Para usar este programa es necesario tener instalados:

=over 4

=item exifautotran

=item imagemagick

=back

=head1 SEE ALSO

B<slide>, B<dogallery>, B<mkindex>

=head1 BUGS

No hay fallos conocidos en este script. Por favor informe de cualquier
fallo al autor.

Parches para mejoras o errores, comentarios y sugerencias serán
bienvenidos.

=head1 COPYRIGHT & LICENSE

Copyright 2013 el autor.

Todos los derechos reservados.

Puede usar, copiar, modificar, distribuir y vender este software, reconociendo a
su autor original y de acuerdo con los términos de la licencia GPL. (GNU General
Public License).

I<No se dan garantías de ningun tipo. Use este software a su propio riesgo.>

=head1 AUTHOR

Luís M. Arocha Hernández <lah.data@gmail.com>

=cut
# }}}
#==============================================================================#
# ENVIRONMENT                                                                  #
#==============================================================================#
# {{{ Modulos y pragmas
use strict;
use CommonFunc qw/:all/;
use Getopt::Std;

# }}}
# {{{ Constantes (o casi)
my $HOME=$ENV{HOME};
our $VERSION = substr q$Revision: 3.1 $, 10;

# }}}
# {{{ Variables
my $curdir = `pwd`;
my $DEST1  = $HOME.'/Dropbox/Photos/Familiar';
my $DEST2  = '/pub/fotos';
my $dir;
my $year;
my %opt;
chomp $curdir;

# }}}
# {{{ Parametros
getopts( 'htuvVrg', \%opt ) or usage('Fallo parámetros');
help()    if $opt{h};
usage()   if $opt{u};
if ($opt{V}){version();exit 1;}
$dir = shift;
usage('Se necesita el nombre de un directorio') unless -d $dir;
usage('El nombre no se ajusta a aaaa*')
    unless $dir =~ /^20\d\d/;
$dir   =~ s/\/$//;
$DEST1 =~ s/\/Familiar// if $opt{g};
$year  = substr( $dir, 0, 4 );

# }}}
#==============================================================================#
# MAIN                                                                         #
#==============================================================================#
# {{{
# Checks
if ( !-d "$DEST2" ) {
    die "No existe destino 1: $DEST2\n";
}
if ( !-d "$DEST1" ) {
    die "No existe destino 2: $DEST1\n";
}
# }}}
# {{{
# Adecuar imagenes
print "Adecuar imagenes: rename/rotate/chmod\n" if $opt{v};
do_system("rename 's/JPG/jpg/' $dir/*");
do_system("cd $dir;renrot *.jpg>/dev/null") if $opt{r};
do_system("chmod -x $dir/*.jpg");

# }}}
# {{{
# Crear thumbnails en Dropbox
print "Creando thumbnails\n" if $opt{v};
do_system("mkdir -p $DEST1/$dir");
opendir DIR, $dir or die "No se puede abrir $dir\n";
while ( my $f = readdir(DIR) ) {
    next unless $f =~ /\.jpg$/;
    next unless -f "$dir/$f";
    print "  $f\n" if $opt{v};
    do_system("convert -scale 1024x768 $dir/$f $DEST1/$dir/1024-$f");
}
closedir DIR;

# }}}
# {{{
# Mover directorio a su sitio.
if ($dir    =~ "$DEST2" or
    $curdir =~ "$DEST2"){
    print "No se mueve a $DEST2\n";
} else {
    print "Moviendo a $DEST2\n" if $opt{v};
    do_system("mkdir -p $DEST2/$year/");
    do_system("mv $dir $DEST2/$year/");
}
exit 0;
# }}}
#==============================================================================#
# FUNCTIONS                                                                    #
#==============================================================================#
# {{{
sub do_system {
    my $t = shift;
    if ( $opt{t} ) {
        print "$t\n";
    } else {
        print "$t\n";
        system $t;
    }
}

# }}}
