#!/bin/bash
### Busca recursivamente ficheros con nombre que no son UTF8 validos
grep-invalid-utf8 () {
      perl -l -ne '/^([\000-\177]|[\300-\337][\200-\277]|[\340-\357][\200-\277]{2}|[\360-\367][\200-\277]{3}|[\370-\373][\200-\277]{4}|[\374-\375][\200-\277]{5})*$/ or print'
}
find | grep-invalid-utf8
