#!/bin/bash
### Descarga de metacpan la documentación de un módulo. La formatea y presenta
rm -rf /tmp/pd
curl --fail --silent -N --url "http://api.metacpan.org/pod/$1?content-type=text/x-pod" >/tmp/pd
perldoc /tmp/pd
rm -rf /tmp/pd
