#!/bin/bash
### Elimina un fichero de la lista de descargas de mldonkey
# Luís M. Arocha Hernández
if [ ! -d /pub/mldonkey ]; then
    echo Fail. No mldonkey here.
    exit 1
fi
/bin/nc -q 2 localhost 4000 >/dev/null <<EOF
auth luis $MLPASS
cancel $@
confirm yes
q
EOF
