#!/usr/bin/perl
#==============================================================================#
# POD                                                                          #
#==============================================================================#
# {{{
=encoding utf-8

=head1 NAME

B<mlfile> - Indica de que tipo es un fichero que se está bajando en mldonkey

=head1 SYNOPSIS

=over 4

=item mlfile [-h|--help|-u|-V|--version]

=item mlfile [-v] F<NUM>

=back

=head1 DESCRIPTION

Indica de que tipo es un fichero que se está bajando en mldonkey

=head1 ARGUMENTS

F<NUM> es el número del fichero en la cola de bajada de mldonkey.

=head1 OPTIONS

=over 4

=item B<-h> Muestra la información de ayuda completa.

=item B<-u> Muestra la información básica de uso (SYNOPSIS).

=item B<-v> Muestra información detallada durante la ejecución.

=item B<-V> Muestra la versión del comando y los módulos usados.

=back

=head1 BUGS

No hay fallos conocidos en este script. Por favor informe de cualquier fallo al autor.

Parches para mejoras o errores, comentarios y sugerencias serán bienvenidos.

=head1 SEE ALSO

Este comando pertenece a un conjunto de comandos que comprende: B<ml>, B<mlbaja>, B<baja>,
B<mlrate>, B<mlren>, B<mlpause>, B<mlresume> y B<mldel> para el tratamiento de la cola de bajada de
mldonkey.

=head1 COPYRIGHT & LICENSE

Copyright 2013 el autor.

Todos los derechos reservados.

Puede usar, copiar, modificar, distribuir y vender este software, reconociendo a su autor original y
de acuerdo con los términos de la licencia GPL. (GNU General Public License).

I<No se dan garantías de ningun tipo. Use este software a su propio riesgo.>

=head1 AUTHOR

Luís M. Arocha Hernández <lah.data@gmail.com>

=cut

# }}}
#==============================================================================#
# ENVIRONMENT                                                                  #
#==============================================================================#
# {{{ Constantes (o casi)
our $VERSION = substr q$Revision: 3.1 $, 10;

# }}}
# {{{ Parametros
my $num = shift;        # Number of file to show

# }}}
#==============================================================================#
# MAIN                                                                         #
#==============================================================================#
# {{{
# Comprobamos que estamos en la maquina correcta
die "Fail. No mldonkey here\n" unless -d '/pub/mldonkey';
# }}}
# {{{
# Leemos salida comando mlinfo
open FILE, "mlinfo $num|" or die "$@";
while (<FILE>) {
    last if /urn:/;
}
close FILE;

# }}}
# {{{
# Formateamos datos
chop;
s/ *\(//;
s/:/_/g;
$name = $_;
$name =~ s{^}{/pub/mldonkey/temp/};
$name =~ s/\n.*/\n/;
$name =~ s/urn_btih_/BT-/;

# }}}
# {{{
# Mostramos
if (! -e $name ) {
    $name =~ s/urn_ed2k_//;
    print "Not found : " unless -e $name;
}
print "$name\n";
exit 0;

# }}}
