#!/bin/sh
### Pod2text wrapper for perl < 5.22 (fails with utf)
ver=$(perl -V|head -1 |perl -ane 'print $F[7]')
if [ "$ver" -lt "22" ]; then
    /usr/bin/pod2text $* |latutf
else
    /usr/bin/pod2text $*
fi
