#!/usr/bin/perl
#==============================================================================#
# POD                                                                          #
#==============================================================================#
# {{{
=encoding utf-8

=head1 NAME

B<podadir> - Borra directorios que estén vacíos

=head1 SYNOPSIS

=over 4

=item podadir [-h|--help|-u|-V|--version]

=item podadir [-v]

=back

=head1 DESCRIPTION

Borra todos los directorios descendientes que estén vacíos. Realiza el
borrado desde el más interno hasta el menos internos, así se borrarán
también los directorios que sólo tienen directorios vacíos.

=head1 OPTIONS

=over 4

=item B<-h> 

Muestra la información de ayuda completa.

=item B<-u> 

Muestra la información básica de uso (SYNOPSIS).

=item B<-v> 

Muestra información detallada durante la ejecución.

=item B<-V> 

Muestra la versión del comando y los módulos usados.

=back

=head1 BUGS

No hay fallos conocidos en este script. Por favor informe de cualquier
fallo al autor.

Parches para mejoras o errores, comentarios y sugerencias serán
bienvenidos.

=head1 COPYRIGHT & LICENSE

Copyright 2013 el autor.

Todos los derechos reservados.

Puede usar, copiar, modificar, distribuir y vender este software, reconociendo
a su autor original y de acuerdo con los términos de la licencia GPL. (GNU
General Public License).

I<No se dan garantías de ningun tipo. Use este software a su propio riesgo.>

=head1 AUTHOR

Luís M. Arocha Hernández <lah.data@gmail.com>

=cut

# }}}
#==============================================================================#
# ENVIRONMENT                                                                  #
#==============================================================================#
# {{{ Modulos y pragmas
use strict;
use CommonFunc qw/:all/;
use Getopt::Std;

# }}}
# {{{ Constantes (o casi)
our $VERSION = substr q$Revision: 3.1 $, 10;

# }}}
# {{{ Variables
my $count = 0;
my %opt;

# }}}
# {{{ Parametros
getopts("huvV",\%opt) or usage("Fallo parámetros");
help()    if $opt{h};
usage()   if $opt{u};
if ($opt{V}){version();exit 1;}

# }}}
#==============================================================================#
# MAIN                                                                         #
#==============================================================================#
# {{{
open FILE,"find -type d|tac|" or die $!;
while (<FILE>){
    chomp;
    if (rmdir){
        $count++;
        print "Borrado $_\n" if $opt{v};
    }
}
close FILE;

# }}}
# {{{ Resultado
print "Borrados $count directorios\n";
exit 0;

# }}}
