#!/usr/bin/perl
#==============================================================================#
# POD                                                                          #
#==============================================================================#
# {{{
=encoding utf-8

=head1 NAME

B<push> - Mueve ficheros a un directorio

=head1 SYNOPSIS

=over 4

=item push [-h|--help|-u|-V|--version]

=item push [-v] [-t] DIR F<FILE>...

=back

=head1 DESCRIPTION

Mueve ficheros a un directorio.

=head1 ARGUMENTS

El primer argumento es el directorio de destino. El resto son los ficheros a
mover.

El nombre del directorio puede ser igual a uno de los ficheros a mover.

=head1 OPTIONS

=over 4

=item B<-h>, B<--help> 

Muestra la información de ayuda completa.

=item B<-t> 

Test mode. No ejecuta. Solo muestra lo que se haría.

=item B<-u> 

Usage. Muestra la información básica de uso (SYNOPSIS).

=item B<-v> 

Verbose. Muestra información detallada durante la ejecución.

=item B<-V>, B<--version> 

Muestra la versión del comando y los módulos usados.

=back

=head1 FILES

Como directorio temporal se usa F<PUSH$$>.

=head1 BUGS

No hay fallos conocidos en este script. Por favor informe de cualquier fallo al
autor.

Parches para mejoras o errores, comentarios y sugerencias serán bienvenidos.

=head1 COPYRIGHT & LICENSE

Copyright 2017 el autor.

Todos los derechos reservados.

Puede usar, copiar, modificar, distribuir y vender este software, reconociendo a
su autor original y de acuerdo con los términos de la licencia GPL. (GNU General
Public License).

I<No se dan garantías de ningun tipo. Use este software a su propio riesgo.>

=head1 AUTHOR

Luís M. Arocha Hernández <lah.data@gmail.com>

=cut

# }}}
#==============================================================================#
# ENVIRONMENT                                                                  #
#==============================================================================#
# {{{ Modulos y pragmas
use 5.10.0;
use strict;
use CommonFunc qw/:all/;
use Getopt::Std;

# }}}
# {{{ Constantes (o casi)
our $VERSION = substr q$Revision: 3.1 $, 10;
my $tmp='PUSHDIR';

# }}}
# {{{ Variables
my %opt;
my $dir;

# }}}
# {{{ Parametros
getopts('htuvV',\%opt) or usage('Fallo parámetros');
help()    if $opt{h};
usage()   if $opt{u};
if ($opt{V}){version();exit 1;}
usage("Es necesario un directorio de destino") unless $ARGV[0];
$dir = shift;
usage("El directorio de destino ya existe") if -d $dir;
usage("Es necesario al menos un fichero a mover") unless $ARGV[0];

# }}}
#==============================================================================#
# MAIN                                                                         #
#==============================================================================#
# {{{
print "Creando directorio temporal $tmp\n" if $opt{v};
if (! $opt{t}){
    mkdir $tmp or die $!;
}
print "Moviendo ficheros\n" if $opt{v};
foreach my $f (@ARGV){
    my $cmd = 'mv '.($opt{v}?'-v ':'')."'$f' $tmp/";
    if ($opt{t}){
        print "$cmd\n";
    } else {
        system $cmd;
    }
}
print "Renombrando directorio temporal\n" if $opt{v};
if (!$opt{t}){
    rename $tmp, $dir or die $!;
}

exit 0;

# }}}
