#!/usr/bin/perl
### print a terminal-wide ruler
my $ruler = "....:....1....:....2....:....3....:....4....:....5....:....6.........7....:....8....:....9....:....0"x3;
print substr($ruler,0,$ENV{COLUMNS});
