#!/usr/bin/perl
#==============================================================================#
# POD                                                                          #
#==============================================================================#
# {{{
=encoding utf-8

=head1 NAME

B<sortlen> - Ordena el fichero de entrada por la longitud de la linea

=head1 SYNOPSIS

=over 4

=item sortlen [-h|--help|-u|-V|--version]

=item sortlen [-v] [F<FILE>...]

=back

=head1 DESCRIPTION

Lee los ficheros de entrada e imprime su contenido por la salida
estándar ordenando por la longitud de la línea, de menor a mayor.

=head1 ARGUMENTS

Si no se indica fichero de entrada se toma la entrada estándar.

=head1 OPTIONS

=over 4

=item B<-h> 

Muestra la información de ayuda completa.

=item B<-u> 

Muestra la información básica de uso (SYNOPSIS).

=item B<-v> 

Muestra información detallada durante la ejecución.

=item B<-V> 

Muestra la versión del comando y los módulos usados.

=back

=head1 BUGS

No hay fallos conocidos en este script. Por favor informe de cualquier
fallo al autor.

Parches para mejoras o errores, comentarios y sugerencias serán
bienvenidos.

=head1 COPYRIGHT & LICENSE

Copyright 2013 el autor.

Todos los derechos reservados.

Puede usar, copiar, modificar, distribuir y vender este software, reconociendo
a su autor original y de acuerdo con los términos de la licencia GPL. (GNU
General Public License).

I<No se dan garantías de ningun tipo. Use este software a su propio riesgo.>

=head1 AUTHOR

Luís M. Arocha Hernández <lah.data@gmail.com>

=cut

# }}}
#==============================================================================#
# ENVIRONMENT                                                                  #
#==============================================================================#
# {{{ Modulos y pragmas
use strict;
use CommonFunc qw/:all/;
use Getopt::Std;

# }}}
# {{{ Constantes (o casi)
our $VERSION = substr q$Revision: 3.1 $, 10;

# }}}
# {{{ Variables
my %opt;                                        # command line options

# }}}
# {{{ Parametros
getopts("huvV",\%opt) or usage("Fallo parámetros");
help()              if $opt{h};
usage()             if $opt{u};
if ($opt{V}){version();exit 1;}
warn "Args=@ARGV\n" if $opt{v};
# }}}
#==============================================================================#
# MAIN                                                                         #
#==============================================================================#
# {{{
print sort {length($a) <=> length($b)} <>;
exit 0;

# }}}
