#!/usr/bin/perl
### Suma valores del segundo campo usando como clave el primero
while (<>){
    chomp;
    @f=split /\s+/;
    $value{$f[0]}+=$f[1];
    $cuenta{$f[0]}++;
}
foreach (sort keys %value){
    printf "%-6s %3d %8.2f\n",$_, $cuenta{$_}, $value{$_};
    $tvalue+=$value{$_};
    $tcuenta+=$cuenta{$_};
}
printf "%-6s %3d %8.2f\n",'TOTAL', $tcuenta, $tvalue;
# Ejemplo
# A  1
# B  1
# A  2
#
# Resultado
# A 3
# B 1
