#!/usr/bin/perl
### Suma valores numericos en las columnas 1 a n (excepto 0)
while (<>){
    chomp;
    @f=split /\s+/;
    $sum=0;
    for $i(1..$#f){
        $f[$i]=~ s/\.// if $f[$i]=~ /,/;
        $f[$i]=~ s/,/./;
        $sum+=$f[$i]
    }
    print $f[0]. ' '. $sum. "\n";
}
# Ejemplo
# A  1 2 3 4
# B  1 5
#
# Resultado
# A 10
# B 6
