#!/usr/bin/perl
#==============================================================================#
# POD                                                                          #
#==============================================================================#
# {{{
=encoding utf-8

=head1 NAME

B<tinycalc> - Pequeña calculadora

=head1 SYNOPSIS

=over 4

=item tinycalc [-h|--help|-u|-V|--version]

=item tinycalc [-v] F<FILE>

=back

=head1 DESCRIPTION

Pequeña calculadora.

Toma la entrada estándar y emite por la salida estándar.

Usa bc.

=head1 ARGUMENTS

Sin argumentos

=head1 OPTIONS

=over 4

=item B<-h>

Muestra la información de ayuda completa.

=item B<-u>

Muestra la información básica de uso (SYNOPSIS).

=item B<-v>

Muestra información detallada durante la ejecución.

=item B<-V>

Muestra la versión del comando y los módulos usados.

=back

=head1 BUGS

No hay fallos conocidos en este script. Por favor informe de cualquier fallo al autor.

Parches para mejoras o errores, comentarios y sugerencias serán bienvenidos.

=head1 COPYRIGHT & LICENSE

Copyright 2016 el autor.

Todos los derechos reservados.

Puede usar, copiar, modificar, distribuir y vender este software, reconociendo a su autor
original y de acuerdo con los términos de la licencia GPL. (GNU General Public License).

I<No se dan garantías de ningun tipo. Use este software a su propio riesgo.>

=head1 AUTHOR

Luís M. Arocha Hernández <lah.data@gmail.com>

=cut

# }}}
#==============================================================================#
# ENVIRONMENT                                                                  #
#==============================================================================#
# {{{ Modulos y pragmas
use strict;
use CommonFunc qw/:all/;
use Getopt::Std;

# }}}
# {{{ Constantes (o casi)
our $VERSION = substr q$Revision: 3.1 $, 10;

# }}}
# {{{ Variables
my %opt;

# }}}
# {{{ Parametros
getopts('htuvV',\%opt) or usage('Fallo parámetros');
help()              if $opt{h};
usage()             if $opt{u};
if ($opt{V}){version();exit 1;}

# }}}
#==============================================================================#
# MAIN                                                                         #
#==============================================================================#
# {{{
while (<>){
    s/ *=.*//;
    my $line = $_;
    chomp $line;
    $_ = "scale=10;$_" unless /scale=/;
    my $result = `echo "$_"|bc -q`;
    $result = sprintf("%0.2f",$result);
    print "$line = $result\n";
}
exit 0;

# }}}
