#!/bin/sh
### Block known dirty hosts from reaching your machine
echo "# Deleting all webban rules"
iptables -S | grep WEBBAN | sed 's/^-A //;' | \
    while read rule; do 
        iptables -w 5 -D INPUT 1 
    done
echo "# IPs from spamhaus"
for i in $(cat /etc/banned-spamhaus); do
    iptables -w 5 -I INPUT -s $i -m comment --comment WEBBAN-SPAMHAUS -j DROP
done
echo "# IPs from dshield.org"
for i in $(cat /etc/banned-dshield); do
    iptables -w 5 -I INPUT -s $i -m comment --comment WEBBAN-DSHIELD -j DROP
done
echo "# My banned IPs"
for i in `cat /etc/banned-mine|awk '{print $1;}'`; do 
    iptables -w 5 -I INPUT -s $i -m comment --comment WEBBAN-MINE -j DROP 
done

# Block all IP addresses and domains that have attempted brute force SSH login to computer
# iptables -I INPUT -p tcp --dport 22 -i eth0 -m state --state NEW -m recent --set
exit
